# Generated by Django 3.2.1 on 2021-06-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('konspekt', models.IntegerField(null=True)),
                ('autor', models.CharField(max_length=400, null=True)),
                ('vydavatelstvo', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Konspekt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PscObvodu',
            fields=[
                ('psc', models.IntegerField(primary_key=True, serialize=False)),
                ('obvod', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TypOperacie',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nazov', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VekovaSkupina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skupina', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Analyza3Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transakciaId', models.IntegerField()),
                ('konspekt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpapp.konspekt')),
                ('vekovaSkupina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpapp.vekovaskupina')),
            ],
        ),
        migrations.CreateModel(
            name='Analyza2Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transakciaId', models.IntegerField()),
                ('casVytvoreniaTransakcie', models.DateField()),
                ('dlzkaVypozicky', models.IntegerField()),
                ('autor', models.CharField(max_length=50)),
                ('vydavatelstvo', models.CharField(max_length=50)),
                ('konspekt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpapp.konspekt')),
                ('typOperacie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpapp.typoperacie')),
            ],
        ),
        migrations.CreateModel(
            name='Analyza1Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pouzivatelId', models.CharField(max_length=150, null=True)),
                ('vek', models.IntegerField(null=True)),
                ('pohlavie', models.CharField(max_length=4, null=True)),
                ('casVytvoreniaTransakcie', models.DateField(null=True)),
                ('psc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpapp.pscobvodu')),
            ],
        ),
    ]
