# Generated by Django 3.2.1 on 2021-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='katalogId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
