# Generated by Django 3.2.1 on 2021-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0002_alter_pscobvodu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konspekt',
            name='nazov',
            field=models.CharField(max_length=100),
        ),
    ]
