# Generated by Django 3.2.1 on 2021-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0002_alter_analyza1model_pouzivatelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyza1model',
            name='pouzivatelId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
