# Generated by Django 3.2.1 on 2021-06-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0002_katalog_katalogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyza2model',
            name='autor',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='analyza2model',
            name='vydavatelstvo',
            field=models.CharField(max_length=400),
        ),
    ]
