# Generated by Django 3.2.1 on 2021-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0003_alter_konspekt_nazov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pscobvodu',
            name='id',
        ),
        migrations.AlterField(
            model_name='pscobvodu',
            name='psc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
