# Generated by Django 3.2.1 on 2021-05-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0004_auto_20210516_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='url',
            new_name='picture',
        ),
    ]
