# Generated by Django 3.2.1 on 2021-05-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0005_rename_url_images_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AlterField(
            model_name='analyza1model',
            name='casVytvoreniaTransakcie',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='analyza1model',
            name='pohlavie',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='analyza1model',
            name='psc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpapp.pscobvodu'),
        ),
        migrations.AlterField(
            model_name='analyza1model',
            name='vek',
            field=models.IntegerField(null=True),
        ),
    ]
